### ISSUE TITLE
Parallel queries from threads

### ISSUE THREAD

**Issue by akhilman** [zakarumych/edict#1]
Could you please briefly describe how the parallel queries will work?

**Comment by zakarumych** [comment]
Atomic borrows from `&World` (kinda like in [hecs](https://docs.rs/hecs)) will validate that mutable aliases are never created by queries.
Unsafe unchecked version of methods would exist for those who need them.

Stageless scheduler will run systems without conflicts as systems specify ahead of time what components they access and how.
Scheduler will probably live in another crate.

**Comment by akhilman** [comment]
Here is plan to make parallel access possible:
* [ ] Make World::epoch atomic;
* [ ] Implement `query_mut_unchecked`, `query_one_mut_unchecked`, `for_each_mut_unchecked`, `for_each_tracked_mut_unchecked`, `get_mut_unchecked` unsafe methods for `World`;
* [ ] Maybe add a runtime check for aliasing like `hecs` does by `Fetch::borrow` and `Fetch::release`.

**Comment by zakarumych** [comment]
Threading support is implemented using runtime checks.
Unsafe version could be added IF profiling would show that checks is a bottleneck
