### ISSUE TITLE
Is it possible to avoid reschedule if the same schedule is being run again. Without change.

### ISSUE THREAD

**Issue by navneetankur** [zakarumych/edict#23]
https://github.com/zakarumych/edict/blob/923c0379242734171f9c63814787086b14d521f5/src/scheduler.rs#L328
calls reschedule on every run. Is it possible to avoid it?

Moreover a minimal example about flow and task would be nice.

**Comment by navneetankur** [comment]
I see not. It actually seems to check that archtypes have changed before doing anything. And returns early if they have not.
😅

**Comment by zakarumych** [comment]
As you can see in the code, `fn reschedule` returns immediately if archetypes and systems didn't change.

**Comment by navneetankur** [comment]
Yeah thanks.
Great work with library though.
Also, you might want to add a description to repo.
