### ISSUE TITLE
How to get EntityId while iterating over a View?

### ISSUE THREAD

**Issue by navneetankur** [zakarumych/edict#27]
```
fn sys(v: edict::View<(&A, &B>)>) {
    for (a,b) in v {
       //print entityId how?
    }
}
```

Also, is it possible to put `Option<Res<SomeResource>>` as param in system. To prevent panic in case resource is not added yet.

**Comment by zakarumych** [comment]
You get `Entity` in view using `Entities` query.

Currently you can't use `Option<Res<T>>` as system argument, but should be easy to add.

**Comment by navneetankur** [comment]
Thanks a lot. For quick response. :)
