### ISSUE TITLE
NoOpHash could be replaced by nohash_hasher crate

### ISSUE THREAD

**Issue by akhilman** [zakarumych/edict#5]
https://github.com/zakarumych/edict/blob/8f9755e04d3544a43b3d26b2f9b4d874d0e0cf3b/src/hash.rs#L52
could be replaced by https://crates.io/crates/nohash-hasher

**Comment by akhilman** [comment]
Also I would like to make a new crate for `TypeIdSet` like collection and use it in my code.

**Comment by zakarumych** [comment]
`nohash_hasher::NoHashHasher<TypeId>` does not implement `Hasher` 🤷

**Comment by zakarumych** [comment]
In general you are free to take any code from my public repositories and make a crate from it.
As for `TypeIdSet` in particular, I was considering make a microcrate for it myself :)

**Comment by akhilman** [comment]
My bad.
I would like to have something like `HashModuloSet<T: Hash + Eq, S = RandomState>` and `HashModuloMap<K: Hash + Eq, V, S = RandomState>`.

I will open new issue if/when I'll make this microcrate.
